#pragma once
#pragma warning (push)
#pragma warning (disable: 4005)

#include "stdafx.h"
#include "Resource.h"
#include "WorldEditor.h"
#include "ExternLibrary.h"

#include "AttributeGridProperty.h"
#include "AttributeGroupGridProperty.h"
#include "ObjGridCheckProperty.h"

#include "CommonDefine.h"
#include "CommonObjDef.h"
#include "FocusButton.h"
#include "FolderDialog.h"
#include "HelpFunction.h"
#include "ThumbnailGenerator.h"
#include "CommonDockablePane.h"

#include "Scene Explorer\SceneExplorerPane.h"
#include "ObjLibToolbar.h"

#include "SceneObjectTree.h"
#include "AddLightObjectHandler.h"
#include "AddObjectHandler.h"
#include "CloneObjHandler.h"
#include "DragHandler.h"
#include "DragMoveHandler.h"
#include "DragRotateHandler.h"
#include "DragScaleHandler.h"
#include "SelectObjHandler.h"
#include "AddObjOperation.h"
#include "ObjAttributeOperation.h"
#include "EditorAxis.h"
#include "ObjectEditorDlg.h"
#include "ObjectTreeCtrl.h"
#include "SceneObjectManager.h"
#include "SkydomeSettingDlg.h"
#include "ObjAttributePane.h"
#include "SceneEditorDlg.h"
#include "SceneObjectDlg.h"
#include "GrassListCtrl.h"
#include "TerrainGrassDlg.h"
#include "TerrainGrassHandler.h"
#include "TerrainGrassOperation.h"
#include "TerrainHeightDlg.h"
#include "TerrainHeightHandler.h"
#include "TerrainHeightOperation.h"
#include "TerrainTextureDlg.h"
#include "TerrainTextureHandler.h"
#include "TerrainTextureLoadDlg.h"
#include "TerrainTextureOperation.h"
#include "TextureListCtrl.h"
#include "TerrainWaterDlg.h"
#include "TerrainWaterHandler.h"
#include "TerrainWaterOperation.h"
#include "WaterImageCtrl.h"
#include "ImageCtrl.h"
#include "TerrainEditorDlg.h"
#include "Terrain Editor\TerrainEditorPane.h"
#include "EditorPane.h"
#include "EditorTabCtrl.h"
#include "MouseMsgHandler.h"
#include "MouseMsgInterface.h"

#include "LogViewer Pane\LogViewerEdit.h"
#include "LogViewer Pane\LogViewerPane.h"
#include "LogViewer Pane\RichEditLogger.h"
#include "FindResultPane.h"
#include "FindResultList.h"
#include "FindDlg.h"

#include "MainFrame.h"
#include "NewMapConfigDlg.h"
#include "NewMapLoadingDlg.h"
#include "WorldEditorDoc.h"
#include "WorldEditorView.h"

#include "IOperation.h"
#include "OperationManager.h"

#include "Render Interface\WorldEditorCamera.h"
#include "Render Interface\WorldEditorRender.h"
#include "Render Interface\WorldEditorRenderInterface.h"

#include "PVRTextureUtilities.h"
#include "WorldMapManager.h"
#include "MapLoadingDlg.h"
#include "MultiPlatformResPackupDlg.h"
#include "PackupResProgressDlg.h"
#include "FileConvert.h"

#include "SettingCheckProperty.h"
#include "Setting Pane\SettingDlg.h"
#include "Setting Pane\SettingPane.h"

#include "ImageShowDlg.h"
#include "ImageStatic.h"
#include "TextureInfoDlg.h"

#include "WorldEditorConfig.h"

#include "LightmapConfigDlg.h"
#include "LightMapBuildDlg.h"

#pragma warning (pop)