#include "CompiledFiles.h"

#include "WorldEditor.cpp"

#include "AttributeGridProperty.cpp"
#include "AttributeGroupGridProperty.cpp"
#include "ObjGridCheckProperty.cpp"

#include "FocusButton.cpp"
#include "FolderDialog.cpp"
#include "HelpFunction.cpp"
#include "ThumbnailGenerator.cpp"
#include "CommonDockablePane.cpp"

#include "Scene Explorer\SceneExplorerPane.cpp"
#include "ObjLibToolbar.cpp"

#include "SceneObjectTree.cpp"
#include "AddLightObjectHandler.cpp"
#include "AddObjectHandler.cpp"
#include "CloneObjHandler.cpp"
#include "DragHandler.cpp"
#include "DragMoveHandler.cpp"
#include "DragRotateHandler.cpp"
#include "DragScaleHandler.cpp"
#include "SelectObjHandler.cpp"
#include "AddObjOperation.cpp"
#include "ObjAttributeOperation.cpp"
#include "EditorAxis.cpp"
#include "ObjectEditorDlg.cpp"
#include "ObjectTreeCtrl.cpp"
#include "SceneObjectManager.cpp"
#include "SkydomeSettingDlg.cpp"
#include "ObjAttributePane.cpp"
#include "SceneEditorDlg.cpp"
#include "SceneObjectDlg.cpp"
#include "GrassListCtrl.cpp"
#include "TerrainGrassDlg.cpp"
#include "TerrainGrassHandler.cpp"
#include "TerrainGrassOperation.cpp"
#include "TerrainHeightDlg.cpp"
#include "TerrainHeightHandler.cpp"
#include "TerrainHeightOperation.cpp"
#include "TerrainTextureDlg.cpp"
#include "TerrainTextureHandler.cpp"
#include "TerrainTextureLoadDlg.cpp"
#include "TerrainTextureOperation.cpp"
#include "TextureListCtrl.cpp"
#include "TerrainWaterDlg.cpp"
#include "TerrainWaterHandler.cpp"
#include "TerrainWaterOperation.cpp"
#include "WaterImageCtrl.cpp"
#include "ImageCtrl.cpp"
#include "TerrainEditorDlg.cpp"
#include "Terrain Editor\TerrainEditorPane.cpp"
#include "EditorPane.cpp"
#include "EditorTabCtrl.cpp"
#include "MouseMsgHandler.cpp"
#include "MouseMsgInterface.cpp"

#include "LogViewer Pane\LogViewerEdit.cpp"
#include "LogViewer Pane\LogViewerPane.cpp"
#include "LogViewer Pane\RichEditLogger.cpp"
#include "FindResultPane.cpp"
#include "FindResultList.cpp"
#include "FindDlg.cpp"

#include "MainFrame.cpp"
#include "NewMapConfigDlg.cpp"
#include "NewMapLoadingDlg.cpp"
#include "WorldEditorDoc.cpp"
#include "WorldEditorView.cpp"

#include "IOperation.cpp"
#include "OperationManager.cpp"

#include "Render Interface\WorldEditorCamera.cpp"
#include "Render Interface\WorldEditorRender.cpp"
#include "Render Interface\WorldEditorRenderInterface.cpp"

#include "WorldMapManager.cpp"
#include "MapLoadingDlg.cpp"
#include "MultiPlatformResPackupDlg.cpp"
#include "PackupResProgressDlg.cpp"
#include "FileConvert.cpp"

#include "SettingCheckProperty.cpp"
#include "Setting Pane\SettingDlg.cpp"
#include "Setting Pane\SettingPane.cpp"

#include "ImageShowDlg.cpp"
#include "ImageStatic.cpp"
#include "TextureInfoDlg.cpp"

#include "WorldEditorConfig.cpp"

#include "LightmapConfigDlg.cpp"
#include "LightMapBuildDlg.cpp"